### ISSUE TITLE
12.3.1 support

### ISSUE THREAD

**Issue by evenlee** [radianttap/EFI-B550I-Aorus#1]
Hi @radianttap 

Have you tested the EFI on 12.3.1, I have same MB, but met issue to startup.

**Comment by radianttap** [comment]
No. I am staying away from 12.3 due dGPU driver issues. Everything works on 12.2.1 — if you don't have the exact same CPU as me, check if you have setup proper number of cores in the patches.

**Comment by evenlee** [comment]
Thank, I've fixed my issue:)
