### ISSUE TITLE
Low resolution using DP, but don't using HDMI

### ISSUE THREAD

**Issue by aleixsr** [radianttap/EFI-B550I-Aorus#3]
I'm having and issue with low resolution using DP, but don't using HDMI.
Works fine under Big Sur.

Do you have high resolution in OpenCore boot menu?

**Comment by radianttap** [comment]
I use DP with my 4K monitor and see no particular issues. Not sure what could be causing it for you.

**Comment by aleixsr** [comment]
Solved it creating a new EFI from scratch and reinstalling MacOS. If somebody is interested: https://github.com/aleixsr/Ryzentosh

I added you in my credits section.
Thanks for your reply!

**Comment by radianttap** [comment]
The best way to do it :)
